name: Cyber Awareness Thread Bot

on:
  schedule:
    - cron: "0 8 * * *"   # 08:00 UTC (09:00 Lagos)
    - cron: "0 20 * * *"  # 20:00 UTC (21:00 Lagos)
  workflow_dispatch: {}

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot (AI in morning, fallback in evening)
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
          RUN_MODE: ${{ github.event.schedule }}
        run: python tweet_bot.py

      - name: Commit log
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add posted_log.json
          git commit -m "Update posted log [skip ci]" || echo "No changes to commit"
          git push
